application: imageserver
version: 1
runtime: go
api_version: go1

handlers:
- url: /test.html
  static_files: test.html
  upload: test.html
- url: /upload
  script: _go_app
- url: /blobstore
  script: _go_app
